/* ------------------------------------------------------------------ */
/*  Extract tables from a PDF and emit them as an .xlsx workbook        */
/*                                                                       */
/*  Re-uses pdfjs for text extraction and the row + column detector     */
/*  from the PDF-to-CSV tool. Each page becomes either its own sheet    */
/*  or rows in a combined sheet depending on the page-mode setting.    */
/* ------------------------------------------------------------------ */

import * as XLSX from 'xlsx'
import { extractTextFromPdf, isLikelyScanned } from '../pdfExtract'
import {
  findPageMode, findHeaderMode, findRowTolerance, findColTolerance, findNumberMode,
  parseRanges, extractTableFromPage, applyHeaderMode, coerceCell,
} from './compute'

export async function probePdf(file) {
  const extracted = await extractTextFromPdf(file)
  return {
    pages: extracted.numPages,
    totalChars: extracted.totalChars,
    isScanned: isLikelyScanned(extracted.items, extracted.totalChars),
  }
}

/**
 * Build & save an XLSX from a PDF.
 * `options`:
 *   - pageModeId:    'all_one_sheet' | 'sheet_per_page' | 'range_one_sheet'
 *   - pageRangesText (for range mode)
 *   - rowToleranceId / colToleranceId
 *   - headerModeId
 *   - numberModeId
 *   - baseName
 */
export async function buildXlsxFromPdf(file, options = {}, onProgress = () => {}) {
  if (!file) throw new Error('No PDF selected.')

  onProgress({ stage: 'reading', pct: 5, message: 'Reading PDF…' })
  const extracted = await extractTextFromPdf(file)
  if (isLikelyScanned(extracted.items, extracted.totalChars)) {
    const err = new Error(`This looks like a scanned PDF (only ${extracted.totalChars} characters found across ${extracted.numPages} page${extracted.numPages === 1 ? '' : 's'}). OCR isn't in this tool — try the pdfFiller premium tier for scanned PDFs.`)
    err.code = 'SCANNED'
    throw err
  }

  const pageMode    = findPageMode(options.pageModeId)
  const headerMode  = findHeaderMode(options.headerModeId)
  const numberMode  = findNumberMode(options.numberModeId)
  const rowTol      = findRowTolerance(options.rowToleranceId).pt
  const colTol      = findColTolerance(options.colToleranceId).pt
  const baseName    = (options.baseName || file.name.replace(/\.pdf$/i, '') || 'extracted').replace(/[^a-z0-9-]+/gi, '-')

  // Determine which pages to extract
  let pages = []
  if (pageMode.id === 'range_one_sheet') {
    const parsed = parseRanges(options.pageRangesText, extracted.numPages)
    pages = Array.from(parsed.pages).sort((a, b) => a - b)
    if (pages.length === 0) throw new Error('No valid pages in the supplied range.')
  } else {
    for (let i = 1; i <= extracted.numPages; i++) pages.push(i)
  }

  const itemsByPage = new Map()
  for (const it of extracted.items) {
    if (!itemsByPage.has(it.page)) itemsByPage.set(it.page, [])
    itemsByPage.get(it.page).push(it)
  }

  // Extract one table per page
  const perPage = []
  for (let i = 0; i < pages.length; i++) {
    const p = pages[i]
    const items = itemsByPage.get(p) || []
    const { rows } = extractTableFromPage(items, { rowTolerance: rowTol, colTolerance: colTol })
    perPage.push({ page: p, rows })
    onProgress({
      stage: 'extracting',
      pct: 10 + ((i + 1) / pages.length) * 70,
      message: `Page ${p}: ${rows.length} rows`,
    })
  }

  onProgress({ stage: 'assembling', pct: 85, message: 'Building workbook…' })

  const wb = XLSX.utils.book_new()
  const wantsCoerce = numberMode.id === 'auto'

  if (pageMode.id === 'sheet_per_page') {
    // One sheet per page, named "Page N"
    for (const pp of perPage) {
      if (pp.rows.length === 0) continue
      const { header, body } = applyHeaderMode(pp.rows, headerMode.id)
      const sheet = buildSheet(header, body, wantsCoerce)
      const name = safeSheetName(`Page ${pp.page}`)
      XLSX.utils.book_append_sheet(wb, sheet, name)
    }
    if (wb.SheetNames.length === 0) throw new Error('No rows detected on any of the selected pages.')
  } else {
    // Combined sheet
    const allRows = perPage.flatMap((pp) => pp.rows)
    if (allRows.length === 0) throw new Error('No rows detected.')
    const { header, body } = applyHeaderMode(allRows, headerMode.id)
    const sheet = buildSheet(header, body, wantsCoerce)
    XLSX.utils.book_append_sheet(wb, sheet, safeSheetName('Extracted'))
  }

  // Add a meta sheet so users (and we) know what produced this file
  const meta = XLSX.utils.aoa_to_sheet([
    ['PDF → Excel — extraction summary'],
    [],
    ['Source PDF',    file.name],
    ['Pages',         pages.length],
    ['Mode',          pageMode.label],
    ['Header',        headerMode.label],
    ['Row tolerance', `${rowTol} pt`],
    ['Col tolerance', `${colTol} pt`],
    ['Number mode',   numberMode.label],
    ['Generated by',  'Sonchoy · PDF to Excel'],
  ])
  meta['!cols'] = [{ wch: 18 }, { wch: 36 }]
  XLSX.utils.book_append_sheet(wb, meta, '_meta')

  onProgress({ stage: 'saving', pct: 96, message: 'Saving workbook…' })

  /* SheetJS' writeFile triggers a download in the browser. We capture
     the array buffer instead so we can report the real output size to
     the UI before the download finishes. */
  const arrayBuffer = XLSX.write(wb, { type: 'array', bookType: 'xlsx', compression: true })
  const blob = new Blob([arrayBuffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })
  const fileName = `${baseName}.xlsx`
  triggerDownload(blob, fileName)

  onProgress({ stage: 'done', pct: 100, message: `Saved ${fileName}` })

  return {
    pages: pages.length,
    sheets: wb.SheetNames.filter((n) => n !== '_meta').length,
    outputBytes: blob.size,
    fileName,
    perPage,
  }
}

/* Build a sheet from header + body, applying optional number coercion. */
function buildSheet(header, body, coerce) {
  const aoa = []
  if (header) aoa.push(header)
  aoa.push(...body)

  const sheet = XLSX.utils.aoa_to_sheet(aoa)
  if (!coerce) return autosizeCols(sheet, aoa)

  // Walk every body cell and upgrade text → number where possible
  const startRow = header ? 1 : 0
  for (let r = startRow; r < aoa.length; r++) {
    const row = aoa[r]
    for (let c = 0; c < row.length; c++) {
      const cellRef = XLSX.utils.encode_cell({ r, c })
      const cell = sheet[cellRef]
      if (!cell || typeof cell.v !== 'string') continue
      const coerced = coerceCell(cell.v)
      if (coerced.t === 'n') {
        cell.v = coerced.v
        cell.t = 'n'
        if (coerced.z) cell.z = coerced.z
      }
    }
  }
  return autosizeCols(sheet, aoa)
}

/* Rough auto-size: each column width = max char-count across rows, capped. */
function autosizeCols(sheet, aoa) {
  const cols = (aoa[0] || []).length
  const widths = new Array(cols).fill(8)
  for (const row of aoa) {
    for (let i = 0; i < cols; i++) {
      const v = row[i]
      const len = (v == null ? '' : String(v)).length
      if (len + 2 > widths[i]) widths[i] = Math.min(48, len + 2)
    }
  }
  sheet['!cols'] = widths.map((wch) => ({ wch }))
  return sheet
}

/* SheetJS sheet names: max 31 chars, no /\?*[] characters. */
function safeSheetName(raw) {
  let s = String(raw || 'Sheet').replace(/[\\/?*[\]:]/g, '_')
  if (s.length > 31) s = s.slice(0, 31)
  if (!s) s = 'Sheet'
  return s
}

function triggerDownload(blob, name) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = name
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}
